#!/usr/bin/env python3

from typing import Optional, Any
import subprocess
import os
from pathlib import Path
import logging
import argparse
import json
import re
import shutil

import urllib.request

DISABLE_ALL_STR = "> Disable All"
UPDATE_MULLVAD_STR = "> Update Mullvad"

MULLVAD_SERVER_LIST_EP = "https://api.mullvad.net/www/relays/all/"
PRIVATE_KEY=(Path.home() / "mullvad_priv_key.key").read_text().strip()

""" Script assumes that the wireguard profile names begin with a country code.
    This is the case with the mullvad profiles. """

# TODO: optional close after profile select
# TODO: use wg-quick
# TODO: download/update profiles to $XDG_CONFIG_DIR/rofi_mullvad/$COUNTRY/profile.conf
#       put all other profiles in other sub directories
#       No parsing required after initial download of profiles
# TODO: History is just a subdir with symlinks to the profile, at startup we have to check
#       if a link is dead

COUNTRY_CODES_PATH = Path(os.path.dirname(__file__)) / "country_codes.json"

WG_PROFILE_BASE_DIR = Path.home() / ".config/rofi_mullvad/profiles"
MULLVAD_BASEDIR = WG_PROFILE_BASE_DIR / "mullvad"

WG_HISTORY_DIR = WG_PROFILE_BASE_DIR / "history"
WG_TEMPLATE = ("[Interface]\n"
               "PrivateKey = {priv_key}\n"
               "Address = 10.68.217.186/32,fc00:bbbb:bbbb:bb01::5:d9b9/128\n"
               "DNS = 10.64.0.1\n"
               "\n"
               "[Peer]\n"
               "PublicKey = {pub_key}\n"
               "AllowedIPs = 0.0.0.0/0,::0/0\n"
               "Endpoint = {ipv4_addr_in}:51820\n")


def run_cmd(cmd: list[str], timeout: int=-1, user: Optional[str]=None, envs_extra: Optional[dict[str,str]]=None, cwd: Optional[Path]=None) -> subprocess.CompletedProcess[str]:
    envs = os.environ.copy()
    envs["LC_ALL"] = "C"
    if envs_extra:
        for k,v in envs_extra.items():
            envs[k] = v
    try:
        result = subprocess.run(cmd,
                                capture_output=True,
                                text=True,
                                timeout=timeout if timeout > 0 else None,
                                user=user,
                                env=envs,
                                cwd=cwd)
    except subprocess.TimeoutExpired:
        raise MullvadException(f"Command timed out after {timeout}s: {' '.join(cmd)}")
    except FileNotFoundError:
        raise MullvadException(f"Command not found: {cmd[0]}")
    except PermissionError:
        raise MullvadException(f"Permission denied running: {' '.join(cmd)}")
    except OSError as e:
        raise MullvadException(f"OS error running command: {str(e)}")

    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise MullvadException(f"Command failed with code {result.returncode}: {' '.join(cmd)}" + (f"\n{stderr}" if stderr else ""))
    return result


def sanitize(string) -> str:
    replace_lst = { " ": "_",
                    ".": "_" }
    for k,v in replace_lst.items():
        string = string.replace(k, v)
    return string.lower()


class MullvadException(Exception): pass


class CustomFormatter(logging.Formatter):
    def __init__(self):
        COLOR_GREEN   = "\033[1;32m" #]
        COLOR_BLUE    = "\033[1;34m" #]
        COLOR_YELLOW  = "\033[1;33m" #]
        COLOR_RED     = "\033[1;31m" #]
        COLOR_MAGENTA = "\033[1;35m" #]
        COLOR_WHITE   = "\033[1;37m" #]
        COLOR_RESET   = "\033[0m"    #]

        self._default_fmt = f"{COLOR_GREEN}INFO{COLOR_RESET}  %(message)s"

        self._formats = { 
            logging.DEBUG   : f"{COLOR_WHITE}%(asctime)s {COLOR_BLUE}%(filename)s {COLOR_RESET}DEBUG %(module)3s.%(funcName)-10s %(lineno)3s{COLOR_RESET} %(message)s",
            logging.INFO    : f"{COLOR_WHITE}%(asctime)s {COLOR_BLUE}%(filename)s {COLOR_MAGENTA}INFO{COLOR_RESET}  %(message)s",
            logging.WARNING : f"{COLOR_WHITE}%(asctime)s {COLOR_BLUE}%(filename)s {COLOR_YELLOW}WARN{COLOR_RESET}  %(message)s",
            logging.ERROR   : f"{COLOR_WHITE}%(asctime)s {COLOR_BLUE}%(filename)s {COLOR_RED}ERROR{COLOR_RESET} %(message)s" 
        }
    
    def format(self, record):
        fmt = self._formats.get(record.levelno, self._default_fmt)
        formatter = logging.Formatter(fmt, datefmt='%Y-%m-%d %H:%M:%S')
        return formatter.format(record)


class RofiLine():
    def __init__(self, name: str, target: Any) -> None:
        self.name = name
        self.target = target


class Rofi():
    """ Class for building rofi apps
          add()   will accept a list or a string, you can call this method
                  multiple times and the result will be added to the rofi args
          show()  show rofi, return result
          sort()  Sorts rofi args in alphabetic order
          reset() is called by show() and resets the rofi args

          It will look for a rofi config file in ~/.config/rofi """

    def __init__(self, theme: str="glue_pro_blue"):
        self._lines = []
        self._rofi_cmd = ["rofi", "-dmenu", "-i",  "-theme-str", "window {width: 300px; height: 700px;}"]
        self._theme = theme
        self._div_width = 20

    def sanitize(self, data, extra_opts = []):
        sanitize_list = [' ', '\'', '\"', '\n'] + extra_opts
        for sanitize in sanitize_list:
            data = data.strip(sanitize)
        return data

    def is_installed(self, application):
        try:
            subprocess.call(application, stdout=subprocess.PIPE)
            return True
        except OSError as e:
            pass

    def run_cmd(self, cmd, lines):
        try:
            child = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
            return child.communicate(lines)[0]
        except FileNotFoundError:
            logger.error(f"Failed to run Rofi")

    def lookup(self, name: str):
        """ Find a line in lines that corresponds with given line """
        return next((l.target for l in self._lines if l.name == name), None)

    def show(self, prompt=False):
        if not self.is_installed(["rofi", "-v"]):
            logger.error("ERROR: Rofi is not installed")
            return

        cmd = self._rofi_cmd

        if self._theme:
            cmd += ["-theme", self._theme]

        cmd += ["-p", prompt or ""]

        lines = [str(line.name) for line in self._lines]
        lines_string = '\n'.join(lines).encode("utf-8")

        result = self.run_cmd(cmd, lines_string)
        result = result.decode('utf-8').strip()

        # Fine corresponding line object
        return self.lookup(result) or result

    def sort(self):
        self._lines = sorted(self._lines)

    def add(self, name: str, target: Any):
        self._lines.append(RofiLine(name, target))

    def add_divider(self, length=None, char="-", text: str=""):
        length = self._div_width if length == None else length

        if text:
            dev_len = int((length-(len(text)+2))/2)
            txt = f"{char*dev_len} {text} "
            self.add(txt + char * (length-len(txt)), None)
        else:
            self.add(length*char, None)


class Server():
    def __init__(self, hostname: str, priv_key: str, ipv4_addr_in: str, ipv6_addr_in: str|None, peer_pub_key: str, path: Path):
        self.hostname: str = hostname
        self.priv_key: str = priv_key
        self.ipv4_addr_in: str = ipv4_addr_in
        self.ipv6_addr_in: str|None = ipv6_addr_in
        self.peer_pub_key: str = peer_pub_key
        self.path: Path = path

    def __repr__(self):
        return f"{self.hostname}"

    @classmethod
    def from_json(cls, js: dict, private_key: str, base_dir: Path) -> 'Server':
        """ Initialize from json """
        try:
            return cls(js["hostname"],
                       #js["country_name"],
                       #js["country_code"],
                       private_key,
                       js["ipv4_addr_in"],
                       js["ipv6_addr_in"],
                       js["pubkey"],
                       base_dir / sanitize(js["country_name"]) / f"{js['hostname']}.conf")
        except KeyError as e:
            raise MullvadException(f"Missing key: {e} in\n{json.dumps(js, indent=4)}")

    @classmethod
    def from_path(cls, path: Path) -> 'Server':
        """ Initialize from path """
        try:
            #country_code = path.parent.name
            data = path.read_text()

            priv_key = re.search(r"^PrivateKey = (.*)$", data, re.MULTILINE).group(1)
            pub_key = re.search(r"^PublicKey = (.*)$", data, re.MULTILINE).group(1)
            ipv4_addr_in = re.search(r"^Endpoint = (.*):\d+$", data, re.MULTILINE).group(1)

            return cls(path.stem,
                       #"country name",
                       #country_code,
                       priv_key,
                       ipv4_addr_in,
                       None,
                       pub_key,
                       path)

        except AttributeError as e:
            raise MullvadException(f"Failed to read profile, missing key for {path}: {e}")

    def to_profile(self):
        return WG_TEMPLATE.format(priv_key     = self.priv_key,
                                  pub_key      = self.peer_pub_key,
                                  ipv4_addr_in = self.ipv4_addr_in)

    def write(self, base_dir: Path|None=None):
        """ Write profile to path """
        if base_dir:
            path = base_dir / self.path.name
        else:
            path = self.path

        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(self.to_profile())
        except (FileNotFoundError, PermissionError, UnicodeDecodeError) as e:
            raise MullvadException(e)

        logger.debug(f"Wrote {self.hostname} to: {path}")

    def add_to_history(self, hist_dir: Path):
        try:
            hist_dir.mkdir(parents=True, exist_ok=True)
            link = hist_dir / self.path.name

            # When we click a history item, self.path is a link
            if self.path.is_symlink():
                target = self.path.resolve()
            else:
                target = self.path

            link.unlink(missing_ok=True)
            link.symlink_to(target)
            logger.debug(f"Added {self.hostname} to history")
        except (FileNotFoundError, PermissionError, UnicodeDecodeError) as e:
            raise MullvadException(e)

    def notify(self, summary: str, body: str, t_ms: int=10000):
        if t_ms >= 0:
            try:
                run_cmd(["notify-send", "--app-name=Mullvad", f"--expire-time={t_ms}",
                             f"--urgency=normal", f"Mullvad: {summary}", body])
            except MullvadException as e:
                logger.error(e)

    def is_active(self) -> bool:
        try:
            run_cmd(["sudo", "wg", "show", self.hostname])
            return True
        except MullvadException as e:
            return False

    def activate(self):
        run_cmd(["sudo", "wg-quick", "up", str(self.path)])
        logger.info(f"Activating: {self.hostname}")
        self.notify("Activated profile", self.hostname)

    def deactivate(self):
        run_cmd(["sudo", "wg-quick", "down", str(self.path)])
        logger.info(f"Deactivating: {self.hostname}")
        self.notify("Deactivated profile", self.hostname)

    def toggle(self):
        if self.is_active():
            self.deactivate()
        else:
            self.activate()


class Mullvad():
    def __init__(self, private_key: str, base_dir: Path):
        self._private_key = private_key
        self._base_dir = base_dir

    def req_mullvad_server_list(self, url: str=MULLVAD_SERVER_LIST_EP, timeout: int=10):
        if not self._private_key:
            raise MullvadException(f"No key specified")

        req = urllib.request.Request(
            MULLVAD_SERVER_LIST_EP,
            headers={"Content-Type": "application/json"},
            method="GET"
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                if resp.status >= 400:
                    raise MullvadException(f"{req.full_url}, {resp.status}, {resp.reason}, {resp.headers}")
                js = json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            raise MullvadException(f"HTTP error: {e.code} {e.reason}")
        except urllib.error.URLError as e:
            raise MullvadException(f"URL error: {e.reason}")
        except json.JSONDecodeError as e:
            raise MullvadException(f"Invalid JSON response: {e}")
        except Exception as e:
            raise MullvadException(f"Unexpected error: {e}")

        servers: list[Server] = []
        for server_js in js:
            if server_js["type"] != "wireguard":
                continue
            servers.append(Server.from_json(server_js, self._private_key, self._base_dir))

        return servers

    def write_server_list(self):
        """ Download serverlist, create profiles and write to {base_dir} """
        if not self._private_key:
            raise MullvadException(f"No key specified")

        try:
            shutil.rmtree(self._base_dir, ignore_errors=True)
            logger.debug(f"Removed:{self._base_dir}")
        except (FileNotFoundError, PermissionError) as e:
            raise MullvadException(f"Failed to remove {self._base_dir}: {e}")

        for server in self.req_mullvad_server_list():
            server.write()

        logger.info(f"Wrote mullvad server list to:{self._base_dir}")


class Wireguard():
    def __init__(self, base_dir: Path, ignore_dirs: list[Path]|None=None) -> None:
        self._base_dir = base_dir
        self._ignore_dirs = ignore_dirs or []

    def rec_read_servers(self) -> list[Server]:
        """ Recursively read mullvad profiles from filesystem """
        servers: list[Server] = []
        for p in self._base_dir.rglob("*.conf"):
            for d in self._ignore_dirs:
                if d in p.parents:
                    continue
            servers.append(Server.from_path(p))
        return servers

    def read_servers(self) -> list[Server|Path]:
        """ Read profiles from filesystem one level deep """
        dirs = []
        servers = []
        for p in self._base_dir.iterdir():
            if p.is_dir():
                dirs.append(p)
            if p.is_file() and p.name.endswith(".conf"):
                servers.append(Server.from_path(p))
        return servers + sorted(dirs, key=lambda x: x.name)

    def find_server(self, hostname: str):
        """ Find matching profile by hostname """
        for server in self.rec_read_servers():
            if server.hostname == hostname:
                return server
        raise MullvadException(f"Failed to find server: {hostname}")

    def get_active(self):
        """ Get all active Server objects """
        servers: list[Server] = []
        result = run_cmd(["sudo", "wg", "show", "interfaces"])
        for hostname in result.stdout.split(" "):
            hostname = hostname.strip()
            if not hostname:
                continue
            try:
                servers.append(self.find_server(hostname))
            except MullvadException as e:
                logger.warning(f"Ignoring VPN connection that is not managed by this script: {hostname}")
        return servers


class App():
    def __init__(self) -> None:
        self.parse_args()

    def parse_args(self):
        parser = argparse.ArgumentParser(description="Manage wireguard connections")
        parser.add_argument('-r', '--rofi-theme', help="Rofi theme", metavar="THEME", type=str)
        parser.add_argument('-t', '--toggle-last', help="Toggle last selected profile", action="store_true")
        parser.add_argument('-T', '--toggle', help="Toggle profile")
        parser.add_argument('-m', '--max-history', help="Maximum amount of history items, default=5", metavar="AMOUNT", type=int, default=5)
        parser.add_argument('-n', '--notify-ms',  help="Duration of notification in sec (-1 to disable), default=10", type=int, default=10)
        parser.add_argument('-d', '--disable-all',  help="Disable all profiles", action="store_true")
        parser.add_argument('-p', '--profile-dir',  help="Profile directory", type=Path, default=WG_PROFILE_BASE_DIR)
        parser.add_argument('-H', '--history-dir',  help="History directory", type=Path, default=WG_HISTORY_DIR)
        parser.add_argument('-k', '--mullvad-key',  help="Mullvad private key")

        parser.add_argument('-u', '--update',  help="Update profiles", action="store_true")

        parser.add_argument('-D', '--debug', help="Enable debugging", action='store_true')

        args = parser.parse_args()

        self._rofi_theme = args.rofi_theme
        self._path_history = args.history_dir
        self._max_history = args.max_history
        self._disable_all = args.disable_all
        self._toggle_last = args.toggle_last
        self._toggle = args.toggle
        self._update = args.update
        self._base_dir = args.profile_dir
        self._history_dir = args.history_dir
        self._mullvad_key = args.mullvad_key

        if args.notify_ms < 0:
            self._t_notify_ms = -1
        else:
            self._t_notify_ms = args.notify_ms * 1000

        if args.debug:
            logger.setLevel(logging.DEBUG)
        else:
            logger.setLevel(logging.INFO)

    def get_history(self, hist_dir: Path):
        """ Get profiles from history dir and sort by ctime """
        history: list[Server] = []
        if not hist_dir.is_dir():
            return []
        links = [f for f in hist_dir.iterdir() if f.is_symlink() and f.name.endswith(".conf")]
        for p in links:
            if p.is_symlink() and not p.exists():
                logger.debug(f"Removing dangling history item: {p} -> {p.resolve()}")
                p.unlink()
                continue
            history.append(Server.from_path(p))
        return sorted(history, key=lambda x: x.path.lstat().st_ctime, reverse=True)

    def select_profile(self, src_dir: Path) -> Server|None:
        """ Select profile using rofi """
        server: Server|None = None
        cur_dir: Path|None = src_dir
        prev_dir: Path|None = None

        while not server:
            rofi = Rofi(theme=self._rofi_theme)

            for p in cur_dir.iterdir():
                if p.is_dir():
                    rofi.add(f"> {p.name}", p)
                if p.name.endswith(".conf"):
                    s = Server.from_path(p)
                    rofi.add(str(s), s)

            result = rofi.show()
            if isinstance(result, Path) and result.is_dir():
                prev_dir = cur_dir
                cur_dir = result
            elif isinstance(result, Server):
                logger.debug(f"Selected: {result}")
                return result
            else:
                if cur_dir == src_dir:
                    break
                cur_dir = prev_dir

        logger.debug("no match")

    def run_rofi(self, mullvad: Mullvad, wireguard: Wireguard):

        while True:
            rofi = Rofi(theme=self._rofi_theme)

            for server in wireguard.get_active():
                rofi.add(str(server), server)

            if self._history_dir.is_dir():
                rofi.add_divider(text="history")
                for server in self.get_history(self._history_dir):
                    rofi.add(str(server), server)

            rofi.add_divider()
            rofi.add(DISABLE_ALL_STR, DISABLE_ALL_STR)
            rofi.add(UPDATE_MULLVAD_STR, UPDATE_MULLVAD_STR)
            rofi.add_divider()

            for item in wireguard.read_servers():
                if isinstance(item, Server):
                    rofi.add(item.hostname, item)
                elif isinstance(item, Path) and not item == self._history_dir:
                    rofi.add(f"> {item.name}", item)

            if not (res := rofi.show()):
                return

            # Handle result
            if res == DISABLE_ALL_STR:
                for server in wireguard.get_active():
                    server.deactivate()
            elif res == UPDATE_MULLVAD_STR:
                mullvad.write_server_list()
            elif isinstance(res, Server):
                res.toggle()
                res.add_to_history(self._history_dir)
            elif isinstance(res, Path):
                if server := self.select_profile(res):
                    server.toggle()
                    server.add_to_history(self._history_dir)

    def run(self):
        mullvad = Mullvad(self._mullvad_key, MULLVAD_BASEDIR)
        wireguard = Wireguard(self._base_dir, ignore_dirs=[self._history_dir])

        # Remove all dangling symlinks in history dir
        self.get_history(self._history_dir)

        if self._update:
            mullvad.write_server_list()

        elif self._toggle:
            wireguard.find_server(self._toggle).toggle()

        elif self._disable_all:
            for server in wireguard.get_active():
                server.deactivate()

        elif self._toggle_last:
            if history := self.get_history(self._history_dir):
                history[0].toggle()

        else:
            self.run_rofi(mullvad, wireguard)


logger = logging.getLogger("rofi_vpn")
ch = logging.StreamHandler()
ch.setFormatter(CustomFormatter())
logger.addHandler(ch)

if __name__ == "__main__":
    app = App()
    try:
        app.run()
    except MullvadException as e:
        logger.error(e)
